version: "3"

services:
  edgestack:
    image: opensona/onos-sona-nightly-docker:dev
    restart: always
    ports:
      - "8181:8181" # GUI (HTTP)
     #- "8443:8443" # GUI (HTTPS)
      - "8101:8101" # CLI
      - "6640:6640" # OVSDB
      - "6653:6653" # OpenFlow
    volumes:
      - ./config:/root/onos/config
      - ./keystore:/root/onos/keystore
      - /var/log/edgestack-log:/root/onos/apache-karaf-4.2.8/data/log
    environment:
      - ONOS_APPS=gui,drivers,openflow-base,ovsdb-base,drivers.ovsdb,openstacknetworking
      - JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF8 -Donos.cluster.messaging.minTimeoutMillis=500 -Donos.cluster.messaging.connectionPoolSize=16 -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:+UseContainerSupport -XX:+PrintFlagsFinal
